#!/usr/bin/env python3
# encoding: utf-8
"""Command line interface for PyAR"""

import logging
import sys
import argparse

import pyar.data_analysis.clustering
from pyar.Molecule import Molecule

logger = logging.getLogger('pyar')
handler = logging.FileHandler('clustering.log', 'w')
formatter = logging.Formatter('%(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)

parser = argparse.ArgumentParser()
parser.add_argument('input_files', type=str, nargs='+',
                    help="input xyz files for analysis")

args =  parser.parse_args()
input_files = args.input_files

if len(input_files) < 2:
    print('Not enough files to cluster')
    sys.exit(0)

mols = []
for each_file in input_files:
    print(each_file)
    mol = Molecule.from_xyz(each_file)
    mol.energy = pyar.data_analysis.clustering.read_energy_from_xyz_file(each_file)
    mols.append(mol)
sys.exit()
pyar.data_analysis.clustering.plot_energy_histogram(mols)
selected = pyar.data_analysis.clustering.choose_geometries(mols)
#    selected = remove_similar(mols)
cmd = ['/home/anoop/bin/molden']
fls = []
for one in selected:
    fls.append(one.name + '.xyz')
print(' '.join(cmd + fls))
# subp.check_call(cmd)
