import tempfile
import unittest
from pathlib import Path
from unittest import mock

import numpy as np
import os

from pyar.backends.babel import OBabel, _read_obenergy_value
from pyar.core.molecule import Molecule


class OpenBabelBackendTests(unittest.TestCase):
    def test_optimize_converts_pdb_output_to_xyz_and_reads_energy(self):
        molecule = Molecule(
            ["H", "H"],
            np.array([[0.0, 0.0, 0.0], [0.0, 0.0, 0.74]]),
            name="test",
        )

        def fake_run_command(command, stdout_path=None, stderr_path=None):
            if command[0] == "obminimize":
                Path(stdout_path).write_text(
                    "COMPND    test:0.0 \n"
                    "AUTHOR    GENERATED BY OPEN BABEL 3.1.1\n"
                    "HETATM    1  H   UNL     1       0.000   0.000   0.000  1.00  0.00           H  \n"
                    "HETATM    2  H   UNL     1       0.000   0.000   0.740  1.00  0.00           H  \n"
                )
                return 0
            if command[0] == "obabel":
                Path(stdout_path).write_text(
                    "2\nconverted\nH 0.000000 0.000000 0.000000\nH 0.000000 0.000000 0.740000\n"
                )
                return 0
            if command[0] == "obenergy":
                Path(stdout_path).write_text(
                    "Open Babel Energy Report\n"
                    "TOTAL ENERGY = 2625.5 kJ/mol\n"
                )
                return 0
            raise AssertionError(f"unexpected command: {command}")

        with tempfile.TemporaryDirectory() as tmpdir:
            cwd = Path.cwd()
            try:
                with mock.patch(
                    "pyar.backends.babel.require_executable",
                    side_effect=lambda program, friendly_name=None: program,
                ), mock.patch("pyar.backends.babel.run_command", side_effect=fake_run_command):
                    os.chdir(tmpdir)
                    try:
                        backend = OBabel(molecule)
                        self.assertTrue(backend.optimize())
                    finally:
                        os.chdir(cwd)
            finally:
                pass

            result_xyz = Path(tmpdir) / "result_test.xyz"
            self.assertTrue(result_xyz.exists())
            contents = result_xyz.read_text().splitlines()
            self.assertEqual(contents[0], "2")
            self.assertAlmostEqual(backend.energy, 1.0)
            np.testing.assert_allclose(
                backend.optimized_coordinates,
                np.array([[0.0, 0.0, 0.0], [0.0, 0.0, 0.74]]),
            )

    def test_read_obenergy_value_falls_back_to_last_numeric_token(self):
        value = _read_obenergy_value(
            [
                "header\n",
                "not useful\n",
                "TOTAL ENERGY = -123.456 kcal/mol\n",
            ],
            "fake.ene",
        )

        self.assertEqual(value, -123.456)

    def test_optimize_returns_false_when_energy_report_has_no_numeric_value(self):
        molecule = Molecule(
            ["H", "H"],
            np.array([[0.0, 0.0, 0.0], [0.0, 0.0, 0.74]]),
            name="test",
        )

        def fake_run_command(command, stdout_path=None, stderr_path=None):
            if command[0] == "obminimize":
                Path(stdout_path).write_text(
                    "COMPND    test:0.0 \n"
                    "AUTHOR    GENERATED BY OPEN BABEL 3.1.1\n"
                    "HETATM    1  H   UNL     1       0.000   0.000   0.000  1.00  0.00           H  \n"
                    "HETATM    2  H   UNL     1       0.000   0.000   0.740  1.00  0.00           H  \n"
                )
                return 0
            if command[0] == "obabel":
                Path(stdout_path).write_text(
                    "2\nconverted\nH 0.000000 0.000000 0.000000\nH 0.000000 0.000000 0.740000\n"
                )
                return 0
            if command[0] == "obenergy":
                Path(stdout_path).write_text(
                    "Open Babel Energy Report\n"
                    "XYZ\n"
                )
                return 0
            raise AssertionError(f"unexpected command: {command}")

        with tempfile.TemporaryDirectory() as tmpdir:
            cwd = Path.cwd()
            try:
                with mock.patch(
                    "pyar.backends.babel.require_executable",
                    side_effect=lambda program, friendly_name=None: program,
                ), mock.patch("pyar.backends.babel.run_command", side_effect=fake_run_command):
                    os.chdir(tmpdir)
                    try:
                        backend = OBabel(molecule)
                        self.assertFalse(backend.optimize())
                    finally:
                        os.chdir(cwd)
            finally:
                pass


if __name__ == "__main__":
    unittest.main()
